export const sample_services: any[] = [
  {
    id:'1',
    name: 'WordPress',
    time: '01',
    price: 50,
    favorite: false,
    //origins: ['Sri Lanka'],
    stars: 4.5,
    imageUrl: 'assets/5.jpg',
    tags: ['website','Content', 'web development'],
  },
  {
    id:'2',
    name: 'Web Development',
    price: 20,
    time: '02',
    favorite: true,
    //origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/3.jpg',
    tags: ['Design', 'web development'],
  },
  {
    id:'3',
    name: 'App Development',
    price: 5,
    time: '10-15',
    favorite: false,
    //origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/4.jpg',
    tags: ['website','Android'],
  },
  {
    id:'4',
    name: 'UI Design',
    price: 2,
    time: '15-20',
    favorite: true,
    //origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/5.jpg',
    tags: ['website', 'UI'],
  },
  {
    id:'5',
    name: 'UX Design',
    price: 11,
    time: '40-50',
    favorite: false,
    //origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/6.jpg',
    tags: ['UX Design', 'Design'],
  },
  {
    id:'6',
    name: 'Content Writing',
    price: 9,
    time: '40-50',
    favorite: false,
   // origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/7.jpg',
    tags: ['Content','web development', 'Website'],
  },
]
export const sample_tags:any[] = [
  { name: 'All', count: 6 },
  { name: 'website', count: 4 },
  { name: 'Content', count: 2 },
  { name: 'web development', count: 3 },
  { name: 'Design', count: 2 },
  { name: 'Android', count: 1 },
  { name: 'UI', count: 1 },
  { name: 'UX Design', count: 1 },
]
