# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: push

env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Build Angular application
      run: |
        ng build

    - name: Test Angular and Node.js applications
      run: |
        ng test
        npm test
